package:
  name: dalphaball

requirements:
  build:
    - python
    - {{ compiler('c') }}
    - make
    - gfortran_{{ target_platform }}
    - gmp

  host:
    - libgfortran-ng
    - gmp

  run:
    - libgfortran-ng
    - gmp

# test:
#  commands:
#    - dalphaball

about:
  home: http://rosettacommons.org
